version: "3.9"

services:
  taiko-node-dashboard:
    image: wolfderechter/taiko-node-dashboard:latest
    ports:
      - "7744:80"
  taiko-node-systeminfo:
    image: wolfderechter/taiko-node-systeminfo:latest
    ports:
      - "3009:3009"