version: "3.9"

services:
  taiko-node-dashboard:
    image: wolfderechter/taiko-node-dashboard:latest
    ports:
      - "7744:80"
  dojonode-systeminformation:
    image: wolfderechter/dojonode-systeminformation:latest
    ports:
      - "3009:3009"
